### ISSUE TITLE
Question for some concepts: tvm.accept() and account flows

### ISSUE THREAD

**Issue by perfogic** [mnill/venom-crash-course-snippets#2]
Hello, I have readed your documentation on "Message and funds" section https://venom.guide/tvm/basic.
But concept of tvm.accept() is quite new to me, and I don't understand it totally.
Here is my knowledge about tvm.accept(), accounts flow and here is my conclusion on Venom, hope you can fix when something I say is misconcept:
   + C1: When we use some wallet like **Venom Wallet,** we will have seed phrase, from seed phrase we will calculate address from **initState** (by randomNonce, may be this case they use increasing nonce to store all accounts when I reinstall **Venom Wallet** again and paste seed phase and still get all accounts that I created)
   + C2: tvm.accept() is used for accepting to pay for transaction (created from externall message), ex: when I create external message to call send from Account contract, tvm.accept() here is use balance of Account contract to pay for that message instead of using msg.value on message.
   + C3: For example, if I call createAuction from Auction contract actually, flows will like external message from me to my Account, then from Account to Auction contract is outcoming internall message. But I'm not sure if createAuction have tvm.accept() how contract will do ? In my understanding, in internal message will have msg.value and it have to have enough native tokens to pay for message => when it reach tvm.accept() Auction contract will pay for it. However I think when we reach this line, it is computation phase which pass credit phase (Auction balance = Auction balance + msg.value of message), so what is different of using tvm.accept and not using tvm.accpt on this case?

Above is my 3 conclusions, hope you have time to check it :(. Thanks for your time

**Comment by mnill** [comment]
С1: - For simple wallet contract, like EverWallet - Address is hash(hash(code)+hash(data(pubkey+nonce))). Nonce usually 0, it is useful for deploy several wallets for one pubkey.

**Comment by mnill** [comment]
C2: - tvm.accept() and messaging is complicated. 
- For external message there are 10k credit gas and contract must call tvm.accept() to agree to pay for the external message from the contract balance, if tvm.accept() is not called such message will not be collated.
- For internal message, there is no credit gas. Instead using value from msg.value, but contract can use tvm.accept() to agree to continue pay in case of there not enough value in msg.value. Using tvm.accept() for internal messages is anti pattern.

**Comment by mnill** [comment]
С3: tvm.accept() should be used sensibly only for external messages. You already have a smart contract wallet where it is used. In your example, the auction smart contract should not make a "tvm.accept()" call. Instead, you should attach an excess of coins to it to cover the gas costs, and it should return the change to you at the end, for instance, by invoking msg.sender.transfer({value: 0, flag: 64, bounce: false});

Please read dice example to figure out how we deal with gas management https://venom.guide/smart_contracts/wallets

**Comment by perfogic** [comment]
Thank you for your time, I closed issue for not consuming your time but you answered all questions dedicatedly and i appreciate that <3.
I have tried deploy a new contract then try send external message and this helps me understand what is 10k credit gas and tvm.accept().
